Added vm sku policy definition
qbeyond/terraform-azurerm-archetype-lib pull request #22
Opened 2024-03-05 15:21 UTC by QBY-MarkusMaring

# Description

This PR will define a policy to deny certain VM SKUs. This policy is not assigned by default.

# Change overview (tick true):

- [ ] This introduces backward incompatible changes
- [x] This adds a new backward compatible Feature
- [ ] This fixes a Bug

# Version information: 

- Previous Version: `2.3.0`

- Next Version based on [Semantic Versioning](https://semver.org/#summary) (see above): `3.0.0`

# How Has This Been Tested?

- [ ] Terraform apply of CAF in test enironment

# Checklist:

- [x] I have run tests and documented them above
- [x] I have performed a self-review of my own code
- [ ] I have updated the documentation
- [x] I have updated the CHANGELOG

2024-03-06 14:22 UTC, QBY-ThimoLimpert approved these changes
Nice Work!

2024-03-06 14:24 UTC, QBY-ThimoLimpert requested changes
This Policy shoudn't be a deny Policy, but a allow policy.

2024-03-06 14:24 UTC, QBY-ThimoLimpert commented on policy_definitions/vmskus/policy_definition_qby_deny_vm_skus.json
> +    "name": "QBY-Deny-VM-SKUs",
```suggestion
    "name": "QBY-Allowed-VM-SKUs",

```

2024-03-06 14:24 UTC, QBY-ThimoLimpert commented on policy_definitions/vmskus/policy_definition_qby_deny_vm_skus.json
> +        "displayName": "Deny VM SKUs",
```suggestion
        "displayName": "Allowed VM/VMSS SKUs",

```

2024-03-07 09:37 UTC, QBY-ChristianHartmann approved these changes
great work

2024-03-07 13:59 UTC, QBY-ThimoLimpert commented on policy_definitions/vmskus/policy_definition_qby_deny_vm_skus.json
> +                "defaultValue": "DeployIfNotExists",
```suggestion
                "defaultValue": "Deny",

```

2024-03-07 13:59 UTC, QBY-ThimoLimpert commented on policy_definitions/vmskus/policy_definition_qby_deny_vm_skus.json
> +                    "DeployIfNotExists",
```suggestion
                    "Audit",
                    "Deny",

```

2024-03-07 15:17 UTC, QBY-ThimoLimpert approved these changes

2024-03-07 15:17 UTC, merged